name: MemeBot workflow merged

on:
  pull_request:
    branches:
      - develop
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            
            rm -r MemeBot
            git clone https://github.com/AntonZelinsky/MemeBot
            cd MemeBot
            
            touch .env
            echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
            
            python3 -m pip install -r requirements.txt
            python3 alembic upgrade head
            
            sudo touch /etc/systemd/system/python.service
            echo [Unit] >> python.service
            echo Description=MemeBot daemon >> python.service
            echo After=network.target >> python.service
            echo [Service] >> python.service
            echo User=${{ secrets.USERNAME }} >> python.service
            echo WorkingDirectory=/home/${{ secrets.USERNAME }}/MemeBot/ >> python.service
            echo ExecStart= python3 /home/${{ secrets.USERNAME }}/MemeBot/run_pulling.py >> python.service
            echo [Install] >> python.service
            echo WantedBy=multi-user.target >> python.service
            
            sudo systemctl enable python.service
            sudo systemctl daemon-reload
            sudo systemctl start python.service
